- name: Deploy to EC2 Instance
  env:
    SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
    EC2_HOST: ${{ secrets.EC2_HOST }}
    EC2_USER: ${{ secrets.EC2_USER }}
    EC2_PROJECT_DIR: ${{ secrets.EC2_PROJECT_DIR }}
  run: |
    echo "$SSH_PRIVATE_KEY" > key.pem
    chmod 600 key.pem

    ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
      echo "Deploying to EC2..."
      
      # Navigate or clone project if not already present
      if [ ! -d "$EC2_PROJECT_DIR/.git" ]; then
        echo "Cloning repository since .git not found..."
        rm -rf $EC2_PROJECT_DIR
        git clone https://github.com/RihanAnkalgi10/E-commerce.git $EC2_PROJECT_DIR
      fi

      cd $EC2_PROJECT_DIR || exit 1
      echo "Pulling latest code..."
      git pull origin main || exit 1

      echo "Installing dependencies..."
      npm install || exit 1

      echo "Restarting app with PM2..."
      pm2 restart all || pm2 start server.js --name ecommerce-app
      echo "Deployment done!"
    EOF
